### ISSUE TITLE
Server is currently unplayable as mobs are extremely OP and bad effect are not going away 

### ISSUE THREAD

**Issue by LNET-Arns** [LolnetModPack/LolnetAdventurePack#25]
Peptide and mintyyyy both say it's unplayable @Mikhaila666 needs to do some updates.

**Comment by Mikhaila666** [comment]
This is mostly the Endermen problem, which, when it was happening, i mentioned several times we'd fix :)  endermen annoying as hell in that mode. Here's the fix:

His config file is part of the world save, not in configs. He wrote this a long time ago and will redo at some point. The filename is ESM_Options.cfg  Find that and there is a section on endermen:

Enderman {
# Valid Endermen Modes (Slender, Normal)
S:Mode=Slender
B:"Player Teleport"=true

Change S:mode=slender to S;mode=normal
and "player teleport"=false.

**Comment by Mikhaila666** [comment]
While you are doing that, make sure creepergriefing for the server is turned on. I also suddenly don't have perms to somethings, not sure why.

**Comment by Mikhaila666** [comment]
This is now fixed.
